version: '3'

services:
  db:
    container_name: mongo.local
    image: mongo:5
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
